import type { Metadata } from "next";
import { Cairo, Tajawal } from "next/font/google";
import { Box } from "@chakra-ui/react";
import "./globals.css";
import { Providers } from "./providers";
import NavbarDynamic from "./NavbarDynamic";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairo.variable} ${tajawal.variable} antialiased`}
        style={{ fontFamily: 'var(--font-cairo), sans-serif' }}
      >
        <Providers>
          <NavbarDynamic />
          <Box as="main" pt={["72px", "72px"]}>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
